# Generated by Django 5.2.10 on 2026-02-23 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("google_books_id", models.CharField(max_length=20, unique=True)),
                ("title", models.CharField(max_length=200)),
                ("authors", models.JSONField(default=list)),
                ("description", models.TextField(blank=True)),
                ("thumbnail", models.URLField(blank=True)),
                ("page_count", models.IntegerField(blank=True, null=True)),
                ("categories", models.JSONField(default=list)),
                ("average_rating", models.FloatField(blank=True, null=True)),
                ("ratings_count", models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
