# Generated by Django 5.2.10 on 2026-04-11 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0002_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="genres",
            field=models.JSONField(default=list),
        ),
        migrations.DeleteModel(
            name="Review",
        ),
    ]
