# Generated by Django 5.2.10 on 2026-04-12 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collection", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="award",
            name="award_type",
            field=models.CharField(max_length=150),
        ),
    ]
