# Generated by Django 5.2.10 on 2026-03-15 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="classname",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="teachername",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
