# Generated by Django 5.2.10 on 2026-03-20 18:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_classname_user_teachername"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="student_id",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="user",
            name="teacher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="students",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
