# Generated by Django 5.2.10 on 2026-03-23 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shelves", "0002_bookshelfentry_allocated_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookshelfentry",
            name="allocated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
